export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const PLAYLIST_LOADING = 'PLAYLIST_LOADING';
export const PLAYLISTS_LOADING = 'PLAYLISTS_LOADING';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLIST = 'GET_PLAYLIST';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const CLEAR_CURRENT_PLAYLISTS = 'CLEAR_CURRENT_PLAYLISTS';

export const SONG_LOADING = 'SONG_LOADING';
export const GET_SONG = 'GET_SONG';
export const CLEAR_SONG = 'CLEAR_SONG';
